Carlister/ViewModels/Cars/CarDetailsViewModel.cs
using Carlister.Web.ViewModels.Enquiries;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Carlister.Web.ViewModels.Cars
{
    public class CarDetailsViewModel
    {
        public Enquiries.EnquiryViewModel Enquiry { get; set; }
        public BLL.Cars.Car Car { get; private set; }

        public CarDetailsViewModel()
        {
            
        }

        public CarDetailsViewModel(BLL.Cars.Car car)
        {
            this.Car = car;
            this.Enquiry = new EnquiryViewModel(car.CarID);
        }

        public CarDetailsViewModel(BLL.Cars.Car car, EnquiryViewModel enquiry)
        {
            this.Car = car;
            this.Enquiry = enquiry;
            this.Enquiry.CarID = this.Car.CarID;
        }
    }
}

Carlister/ViewModels/Cars/CarListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Carlister.Web.ViewModels.Cars
{
    public class CarListViewModel
    {
        public List<BLL.Cars.Car> Cars { get; set; }

        public CarListViewModel()
        {

        }

        public CarListViewModel(List<BLL.Cars.Car> cars)
        {
            this.Cars = cars;
        }
    }
}

Carlister/ViewModels/Enquiries/EnquiryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Carlister.Web.ViewModels.Enquiries
{
    public class EnquiryViewModel : Common.DTO.IEnquiry
    {
        [HiddenInput]
        public int CarID { get; set; }
        [HiddenInput]
        public int EnquiryID { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public EnquiryViewModel()
        {

        }

        public EnquiryViewModel(int carID)
        {
            this.CarID = carID;
        }
    }
}

Carlister/Controllers/CarController.cs
using Autofac;
using Carlister.Web.ViewModels.Cars;
using Carlister.Web.ViewModels.Enquiries;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carlister.Web.Controllers
{
    public class CarController : Controller
    {
        private ILifetimeScope DiContainer = null;

        public CarController(ILifetimeScope container)
        {
            this.DiContainer = container;
        }

        /// <summary>
        /// View the details of a car and enquiry about it - if you want to
        /// </summary>
        /// <param name="id">CarID of the car you want to view</param>
        /// <returns></returns>
        public ActionResult Index(int? id)
        {
            if (id.HasValue)
            {
                using (var db = this.DiContainer.Resolve<Common.Data.ICarDataSource>())
                {
                    var car = BLL.Cars.Car.GetCar(id.Value, db);

                    if (car != null)
                    {
                        CarDetailsViewModel model = new CarDetailsViewModel(car);

                        return View("Index", model);
                    }
                    else
                        return RedirectToAction(nameof(HomeController.Error), "Home");
                }
            }
            else
                return RedirectToAction(nameof(HomeController.Error), "Home");
        }

        public ActionResult List()
        {
            using (var db = this.DiContainer.Resolve<Common.Data.ICarDataSource>())
            {
                var cars = BLL.Cars.Car.GetCars(db);
                var model = new CarListViewModel(cars);
                return View(model);
            }
        }
    }
}

Carlister/Controllers/EnquiryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Autofac;
using Carlister.Common.Data;
using Carlister.Web.ViewModels.Enquiries;
using Carlister.Web.ViewModels.Cars;

namespace Carlister.Web.Controllers
{
    public class EnquiryController : Controller
    {
        private ILifetimeScope DiContainer;

        public EnquiryController(ILifetimeScope container)
        {
            this.DiContainer = container;
        }

        // GET: Enquiry
        public ActionResult Submit(EnquiryViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = this.DiContainer.Resolve<IEnquiryDataSource>())
                {
                    var enquiry = BLL.Enquiries.EnquiryFactory.CreateEnquiry(model);
                    enquiry.Insert(db);
                }

                return View("ThankYou");
            }
            else
            {
                using (var db = this.DiContainer.Resolve<ICarDataSource>())
                {
                    var car = BLL.Cars.Car.GetCar(model.CarID, db);
                    return View("~/Views/Car/Index.cshtml", new CarDetailsViewModel(car, model));
                }
            }
        }

        public ActionResult List()
        {
            using (var db = this.DiContainer.Resolve<IEnquiryDataSource>())
            {
                return View(BLL.Enquiries.Enquiry.GetEnquiries(db));
            }
        }
    }
}

Carlister/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carlister.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToActionPermanent(nameof(CarController.List), "Car");
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

Carlister/Views/Car/Index.cshtml
@model Carlister.Web.ViewModels.Cars.CarDetailsViewModel
@{
    ViewBag.Title = "Car Details / Enquire";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Car Details</h2>

<section>
    @{ Html.RenderPartial("~/Views/Car/_CarDetails.cshtml", Model.Car); }
</section>
<section>
    @{ Html.RenderPartial("~/Views/Enquiry/_Enquire.cshtml", Model.Enquiry); }
</section>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

Carlister/Views/Car/List.cshtml
@model Carlister.Web.ViewModels.Cars.CarListViewModel
@{
    ViewBag.Title = "List of Cars";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Cars</h2>

<ul class="listOfCars">
    @foreach (var c in Model.Cars)
    {
        <li>
            @{ Html.RenderPartial("_CarListItem", c); }
        </li>
    }
</ul>

Carlister/Views/Car/_CarDetails.cshtml
@using Carlister.BLL.Cars
@using Carlister.Common.Enums
@using Carlister.Web.Controllers

@model Car

<h3 class="bgblue">
    @Html.ActionLink("<", nameof(CarController.List), "Car")
    @Model.Year @Model.Make @Model.Model
</h3>
<div class="carView">
    <content>
        <dl>
            <dt>Make</dt>
            <dd>@Model.Make</dd>

            <dt>Model</dt>
            <dd>@Model.Model</dd>

            <dt>Year</dt>
            <dd>@Model.Year</dd>

            @switch (Model.SaleType)
            {
                case SaleType.PrivateSale:
                {
                    <dt>Contact Name</dt>
                    <dd>@Model.ContactName</dd>
                    <dt>Phone</dt>
                    <dd>@Model.Phone</dd>
                }
                break;
                case SaleType.DealerSale:
                {
                    <dt>Dealer ABN</dt>
                    <dd>@Model.DealerABN</dd>
                }
                break;
            }

            <dt>Email</dt>
            <dd><a href="mailto:@Model.Email">@Model.Email</a></dd>
        </dl>
        <dl class="right">
            @{ Html.RenderPartial("_Price", Model); }
            <dt>Comments</dt>
            <dd>@Model.Comments</dd>
        </dl>
    </content>
</div>

Carlister/Views/Car/_CarListItem.cshtml
@using Carlister.BLL.Cars
@using Carlister.Common.Enums
@using Carlister.Web.Controllers

@model Car

<div class="carView">
    <header>
        <a href="@Url.Action(nameof(CarController.Index), "Car", new { id = Model.CarID })">
            @Model.Year @Model.Make @Model.Model
        </a>
    </header>
    <content>
        <dl>
            <dt>Make</dt>
            <dd>@Model.Make</dd>

            <dt>Model</dt>
            <dd>@Model.Model</dd>

            <dt>Year</dt>
            <dd>@Model.Year</dd>
        </dl>
        <dl class="right">
            @{ Html.RenderPartial("_Price", Model); }
            <dt>Comments</dt>
            <dd title="@Model.Comments">@Model.Comments</dd>
        </dl>
    </content>
    <footer>
        <div class="saleType">
            @(Model.SaleType == SaleType.DealerSale ? "Dealer Sale" : "Private Sale")
        </div>

        @Html.ActionLink("Details / Enquire", nameof(CarController.Index), "Car", new { id = Model.CarID }, new { @class = "btn btn-primary" })
    </footer>
</div>

Carlister/Views/Car/_Price.cshtml
@using Carlister.Common.Enums
@using Carlister.BLL.Tools

@model Carlister.BLL.Cars.Car

@{
    decimal? price = null;

    if (Model.PriceType == PriceType.DAP)
    {
        price = Model.DapPrice;
    }
    else if (Model.PriceType == PriceType.EGC)
    {
        price = Model.EgcPrice;
    }

    string priceString;

    if (price.HasValue)
    {
        priceString = string.Format("${0:#,##0}", price.Value);
    }
    else
    {
        priceString = "-";
    }
}

<dt>@Model.PriceType.GetDescription()</dt>
<dd class="price">
    @priceString
</dd>

Carlister/Views/Enquiry/List.cshtml
@model IEnumerable<Carlister.BLL.Enquiries.Enquiry>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Undocumented Enquiries Listing Page :)</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarID)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarID)
        </td>
    </tr>
}

</table>

Carlister/Views/Enquiry/ThankYou.cshtml
@{ 
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Thank You";
}

<h1>Thank You</h1>
<h4>Thank you for your enquiry</h4>

Carlister/Views/Enquiry/_Enquire.cshtml
@using Carlister.Web.Controllers
@model Carlister.Web.ViewModels.Enquiries.EnquiryViewModel

@using (Html.BeginForm(nameof(EnquiryController.Submit), "Enquiry", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Make an Enquiry</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarID)
        @Html.HiddenFor(model => model.EnquiryID)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", type = "email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit Enquiry" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Carlister/Views/Shared/_Layout.cshtml
@using Carlister.Web.Controllers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Carlister</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Carlister", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List of Cars", nameof(CarController.List), "Car")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Carlister</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>